name: '0.$(Date:yyyy).$(System.PullRequest.PullRequestNumber).$(Rev:r)'
pr:
- 'develop'
- 'release/2*'
trigger: none

pool:
  vmImage: 'windows-latest'
  name: 'Azure Pipelines'
  demands:
  - Pull-Requests -equals true

variables:
- template: 'build-templates/variables.yml'

steps:
- template: 'build-templates/tasks-tools.yml'
- template: 'build-templates/tasks-dependencies.yml'
- template: 'build-templates/tasks-build.yml'
