name: '0.$(Date:yyyy).1.$(Rev:r)'
pr: none
trigger:
  batch: true
  branches:
    include:
    - develop_v1

pool:
  vmImage: 'windows-latest'

variables:
- template: 'build-templates/variables.yml'

steps:
- template: 'build-templates/tasks-tools.yml'
- template: 'build-templates/tasks-dependencies.yml'
- template: 'build-templates/tasks-build.yml'